name: CI

on: push

jobs:
  run:
    name: CI on PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    container: 1maa/php-dev:${{ matrix.php-version }}
    strategy:
      fail-fast: false
      matrix:
        php-version: [ "8.2" ]
    steps:
      - name: Temporary hack to avoid a hang in functional tests
        run: |
          rm /etc/php/cli/conf.d/20-event.ini
          rm /etc/php/cli/conf.d/20-uv.ini
      - uses: actions/checkout@v3
      - run: composer install
      - run: composer cs-fix-ci
      - run: composer test
