name: CI

on: push

jobs:
  run:
    name: CI on PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    container: 1maa/php-dev:${{ matrix.php-version }}
    strategy:
      fail-fast: false
      matrix:
        php-version: [ "8.1", "8.2" ]
    steps:
      - uses: actions/checkout@v3
      - run: composer install
      - run: composer cs-fix-ci
      - run: composer test
